### ISSUE TITLE
Unable to create Abyss

### ISSUE THREAD

**Issue by Garg-Shashwat** [SpacedOutChicken/The-Undead#9]
Great mod, loved it!
But I am unable to create Abyss using Necromancer. I have tried unimproved tiles owned and unowned, and improved tiles too. But it doesn't allow me to do it.

Also, don't know if it is intentional but the undead can receive normal Great People using Educated Elite(Patronage) Policy and vice versa is also possible(playing as Other civilization and getting Undead Great People using the policy).

**Comment by SpacedOutChicken** [comment]
The Necromancer should be able to build the Abyss again.

As for the Educated Elite policy, it's working as intended. You can get Great Persons from any type of civilization using that policy, so players besides Mongolia can be gifted a Khan.
